name: Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.4.0]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '2' # so we can run git diff

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run clean compile
        
    - name: Update lib/ if necessary
      run: |
        git config user.name "lib/ helper"
        git config user.email "actions@users.noreply.github.com"
        git diff lib/ --quiet || (git add lib/ && git commit -m "Regenerate lib/" && git push")

    - name: Check for changes
      run: |
        git diff --exit-code
